# Generated by Django 3.1.6 on 2021-02-11 13:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='WebApp.estate')),
            ],
        ),
    ]
