# Generated by Django 3.1.6 on 2021-02-11 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('WebApp', '0002_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
