# Generated by Django 3.1.6 on 2021-02-16 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('WebApp', '0003_auto_20210211_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.estate'),
        ),
    ]
