# Generated by Django 3.1.6 on 2021-02-22 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0006_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='importance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vote',
            name='choice',
            field=models.CharField(max_length=99),
        ),
    ]
