# Generated by Django 3.1.6 on 2021-03-18 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WebApp', '0009_auto_20210223_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='WebApp.estate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='notify',
            constraint=models.UniqueConstraint(fields=('user', 'estate'), name='unique_notification'),
        ),
    ]
