# Generated by Django 3.1.6 on 2021-03-23 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0010_auto_20210318_1408'),
        ('WebApp', '0011_estate_is_finished'),
    ]

    operations = [
    ]
