# Generated by Django 3.1.6 on 2021-03-26 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebApp', '0012_merge_20210323_1027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Settlement',
        ),
        migrations.AddField(
            model_name='item',
            name='has_everyone_voted',
            field=models.BooleanField(default=False),
        ),
    ]
